version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    environment:
      - NAME=World

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
    command: ["pytest", "test.py"]
